# Common Labels
labels:
  app: "dristi-case-pdf"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "dristi-case-pdf"


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/pucar_dristi_case_pdf"
  tag: v1.0.0-1ea0074cb9041fa0837eb8193c66673cb8c4e2c4
replicas: "1"


healthChecks:
  enabled: false
  livenessProbePath: "/dristi-case-pdf/"
  readinessProbePath: "/dristi-case-pdf/"
    
env: |
  - name: NODE_OPTIONS
    value: "--max-old-space-size=2048"
  - name: SERVER_PORT
    value: "8080"
  - name: PDF_SERVICE_URL
    value: "http://pdf-service:8080"
  - name: FILE_STORE_HOST 
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services

