# Common Labels
labels:
  app: "pdf-service"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "pdf-service"

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "pdf_service_schema"
    image:
      repository: "pdf-service-db"
      tag: pdf-with-qr-2f2ab1ac27-31

  gitSync:
    enabled: true
    repo: "git@github.com:egovernments/configs"
    branch: "master"


# Container Configs
image:
  repository: "pdf-service"
  tag: pdf-with-qr-2f2ab1ac27-31
replicas: "1"
appType: "java-spring"
tracing-enabled: true
data-config-urls: "file:///work-dir/dpg-configs/pdf-service/data-config/summons-issue.json,file:///work-dir/dpg-configs/pdf-service/data-config/summons-issue-qr.json,file:///work-dir/dpg-configs/pdf-service/data-config/schedule-hearing-date.json,file:///work-dir/dpg-configs/pdf-service/data-config/schedule-hearing-date-qr.json,file:///work-dir/dpg-configs/pdf-service/data-config/accept-reschedule-request.json,file:///work-dir/dpg-configs/pdf-service/data-config/accept-reschedule-request-qr.json,file:///work-dir/dpg-configs/pdf-service/data-config/new-hearing-date-after-rescheduling.json,file:///work-dir/dpg-configs/pdf-service/data-config/new-hearing-date-after-rescheduling-qr.json,file:///work-dir/dpg-configs/pdf-service/data-config/mandatory-async-submissions-responses.json,file:///work-dir/dpg-configs/pdf-service/data-config/mandatory-async-submissions-responses-qr.json"
format-config-urls: "file:///work-dir/dpg-configs/pdf-service/format-config/summons-issue.json,file:///work-dir/dpg-configs/pdf-service/format-config/summons-issue-qr.json,file:///work-dir/dpg-configs/pdf-service/format-config/schedule-hearing-date.json,file:///work-dir/dpg-configs/pdf-service/format-config/schedule-hearing-date-qr.json,file:///work-dir/dpg-configs/pdf-service/format-config/accept-reschedule-request.json,file:///work-dir/dpg-configs/pdf-service/format-config/accept-reschedule-request-qr.json,file:///work-dir/dpg-configs/pdf-service/format-config/new-hearing-date-after-rescheduling.json,file:///work-dir/dpg-configs/pdf-service/format-config/new-hearing-date-after-rescheduling-qr.json,file:///work-dir/dpg-configs/pdf-service/format-config/mandatory-async-submissions-responses.json,file:///work-dir/dpg-configs/pdf-service/format-config/mandatory-async-submissions-responses-qr.json"
#healthChecks:
#  enabled: true
#  livenessProbePath: "/pdf-service/health"
#  readinessProbePath: "/pdf-service/health"


# Additional Container Envs
env: |
  - name: DEFAULT_LOCALISATION_TENANT
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: KAFKA_BROKER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: EGOV_EXTERNAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name      
  - name: DB_PORT
    value: "5432"  
  - name: SERVER_PORT
    value: "8080"
  - name: MAX_NUMBER_PAGES
    value: "80"   
  - name: DATA_CONFIG_URLS
    value: {{ index .Values "data-config-urls" | quote }}
  - name: FORMAT_CONFIG_URLS
    value: {{ index .Values "format-config-urls" | quote }}
  - name: EGOV_LOCALISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: EGOV_FILESTORE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
