# Common Labels
labels:
  app: "sbi-svc"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "sbi-backend"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "public_treasury_schema"
    image:
      repository: "pucarsolutionsdev.azurecr.io/sbi-svc-db"
      tag: v1.0.0-0d454a1a68d5969c30b2edc72786a1c76bdb711a

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/sbi-svc"
  tag: v1.0.0-0d454a1a68d5969c30b2edc72786a1c76bdb711a


replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: JAVA_OPTS
    value: "-Xmx192m -Xms192m"
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: SPRING_FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_FLYWAY_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_COLLECTIONSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: collection-services
        name: egov-service-host
  - name: EGOV_FILE_STORE_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-filestore
        name: egov-service-host
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: SBI_TRANSACTION_URL
    valueFrom:
      configMapKeyRef:
        key: sbi-tranction-url
        name: egov-config
  - name: SBI_TRANSACTION_SUCCESS_URL
    valueFrom:
      configMapKeyRef:
        key: sbi-tranction-success-url
        name: egov-config
  - name: SBI_TRANSACTION_FAIL_URL
    valueFrom:
      configMapKeyRef:
        key: sbi-tranction-fail-url
        name: egov-config
  



