name: Pucar-Install Workflow DPG-Dev
# Workflow branch creating cluster against the input.yaml file
on:
  push:
    branches:
      - Dev-0
  pull_request:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    outputs:
      deploy-as-code-changed: ${{ steps.check_files.outputs.deploy-as-code-changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in deploy-as-code
        id: check_files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            deploy-as-code/**

  Terraform_Infra_Creation:
    needs: check-changed-files
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      ARM_CLIENT_ID:  ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET:  ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init - Infra creation
        id: init-Infra
        run: terraform init -backend-config="resource_group_name=pucar-dev" -backend-config="storage_account_name=tfstate1dkna" -backend-config="container_name=pucar-dev-tfstate" -backend-config="key=infra.tfstate" -reconfigure
        working-directory: infra-as-code/terraform/azure-pucar
      - name: Terraform Validate - Infra creation
        id: validate-Infra
        run: terraform validate -no-color
        working-directory: infra-as-code/terraform/azure-pucar
      - name: Terraform Plan - Infra creation
        id: plan-Infra
        run: terraform plan -no-color -input=false -var-file="tfvars/pucar/dev.tfvars" -var "db_password=${{ secrets.TF_VAR_db_password }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
        working-directory: infra-as-code/terraform/azure-pucar
      # - name: Terraform Apply - Infra creation
      #   id: apply-Infra
      #   run: terraform apply -no-color -input=false -auto-approve -var-file="tfvars/pucar/dev.tfvars" -var "db_password=${{ secrets.TF_VAR_db_password }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
      #   working-directory: infra-as-code/terraform/azure-pucar
      - name: Generate kubeconfig
        run: |
          az aks get-credentials --resource-group "pucar-dev" --name "dev"
          cat ~/.kube/config > kubeconfig
      - name: Kubectl setup
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        id: install
      - name: Verify kubectl configuration
        run: kubectl config view
      - name: Verify kubectl get nodes
        run: |
          kubectl get nodes
      # - name: Updating the terraform output data in environment.yaml files for deployment
      #   run: terraform output -json | go run ../scripts/envYAMLUpdater.go
      #   working-directory: infra-as-code/terraform/azure-pucar

  DIGIT-deployment:
    needs: Terraform_Infra_Creation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Generate kubeconfig
        run: |
          az aks get-credentials --resource-group "pucar-dev" --name "dev"
          cat ~/.kube/config > kubeconfig
      - name: Kubectl setup
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        id: install
      - name: Creating namespace
        run: kubectl create namespace egov
        continue-on-error: true
      - name: Verify kubectl get nodes
        run: |
          kubectl get nodes
      - name: Install sops
        run: |
          sudo apt update
          sudo apt install -y age
          mkdir -p $HOME/.config/sops/age/
          echo # public key: ${{ secrets.PUBLIC_AGE_KEY }} > $HOME/.config/sops/age/keys.txt
          echo ${{ secrets.PRIVATE_AGE_KEY }} >> $HOME/.config/sops/age/keys.txt
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
          chmod +x sops-v3.7.1.linux
          sudo mv sops-v3.7.1.linux /usr/local/bin/sops
      - name: sops decryption
        run: |
          sudo sops --decrypt --age ${{ secrets.PUBLIC_AGE_KEY }} $HOME/work/pucar-DevOps/pucar-DevOps/deploy-as-code/charts/environments/dev-env-secrets.yaml > env-secrets1.yaml
          cp env-secrets1.yaml $HOME/work/pucar-DevOps/pucar-DevOps/deploy-as-code/charts/environments/dev-env-secrets.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest' # Specify the version of Helm
      - name: Install Helmfile
        uses: helmfile/helmfile-action@v1.9.0
        with:
          helmfile-version: 'v0.150.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff
      - name: DIGIT Deployment with updated tag
        run: |
          advocate_commitId=$(git ls-remote https://github.com/pucardotorg/dristi.git dev_backend_advocate_bis | awk '{print $1}')
          echo "Advocate Commit ID: $advocate_commitId"

          case_commitId=$(git ls-remote https://github.com/pucardotorg/dristi.git dev_backend_case_bis | awk '{print $1}')
          echo "Case Commit ID: $case_commitId"

          digit_ui_commitId=$(git ls-remote https://github.com/pucardotorg/dristi.git user-registration-flow | awk '{print $1}')
          echo "DIGIT-UI Commit ID: $digit_ui_commitId"

          helmfile -f digit-helmfile.yaml apply --include-needs=true \
           --set advocate.image.tag=v1.0.0-${advocate_commitId} \
           --set advocate.initContainers.dbMigration.image.tag=v1.0.0-${advocate_commitId} \
           --set case.image.tag=v1.0.0-${case_commitId} \
           --set case.initContainers.dbMigration.image.tag=v1.0.0-${case_commitId} \
           --set digit-ui.image.tag=v1.0.0-${digit_ui_commitId}
        env:
          HELMFILE_ENV: dev
        working-directory: deploy-as-code

