name: Pucar-Install Workflow Solutins-Dev
on:
#  push:
#   branches:
#     - Solutions-Pipeline
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:
  repository_dispatch:

permissions:
  id-token: write
  contents: write
jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    outputs:
      deploy-as-code-changed: ${{ steps.check_files.outputs.deploy-as-code-changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in deploy-as-code
        id: check_files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            deploy-as-code/**

#  Terraform_Infra_Creation:
#    needs: check-changed-files
#    runs-on: ubuntu-latest
#    env:
#      TF_IN_AUTOMATION: "true"
#      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
#      ARM_CLIENT_ID: ${{ secrets.AZURE_SOLUTIONS_CLIENT_ID }}
#      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SOLUTIONS_CLIENT_SECRET }}
#      db_password: ${{ secrets.TF_VAR_db_password }}
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v2
#
#      - name: Azure login
#        uses: azure/login@v2
#        with:
#          creds: ${{ secrets.SOLUTIONS_AZURE_CREDENTIALS }}
#
#      - name: Terraform init - Infra creation
#        id: init-Infra
#        run: |
#          terraform --version
#          terraform init -backend-config="resource_group_name=pucar-solutions-dev" -backend-config="storage_account_name=tfstate771y4" -backend-config="container_name=pucar-solutions-dev-tfstate" -backend-config="key=infra.tfstate" -reconfigure
#        working-directory: infra-as-code/terraform/azure-pucar
#
#      - name: Terraform Validate - Infra creation
#        id: validate-Infra
#        run: terraform validate -no-color
#        working-directory: infra-as-code/terraform/azure-pucar
#
#      - name: Terraform Plan - Infra creation
#        id: plan-Infra
#        run: terraform plan -no-color -input=false -var-file="tfvars/pucar-solutions/dev.tfvars" -var "db_password=${{ secrets.TF_VAR_db_password }}" -var "ARM_SUBSCRIPTION_ID=${{ env.ARM_SUBSCRIPTION_ID }}" -var "ARM_TENANT_ID=${{ env.ARM_TENANT_ID }}" -var "ARM_CLIENT_ID=${{ env.ARM_CLIENT_ID }}" -var "ARM_CLIENT_SECRET=${{ env.ARM_CLIENT_SECRET }}"
#        working-directory: infra-as-code/terraform/azure-pucar
#
#      - name: Terraform Apply - Infra creation
#        id: apply-Infra
#        run: terraform destroy -auto-approve -var-file="tfvars/pucar-solutions/dev.tfvars" -var "db_password=${{ secrets.TF_VAR_db_password }}"  -var "ARM_SUBSCRIPTION_ID=${{ env.ARM_SUBSCRIPTION_ID }}" -var "ARM_TENANT_ID=${{ env.ARM_TENANT_ID }}" -var "ARM_CLIENT_ID=${{ env.ARM_CLIENT_ID }}" -var "ARM_CLIENT_SECRET=${{ env.ARM_CLIENT_SECRET }}"
#        working-directory: infra-as-code/terraform/azure-pucar

#      - name: Generate kubeconfig
#        run: |
#          az aks get-credentials --resource-group "pucar-solutions-dev" --name "solutions-dev"
#          cat ~/.kube/config > kubeconfig
#      - name: Kubectl setup
#        uses: azure/setup-kubectl@v3
#        with:
#          version: 'latest'
#        id: install
#
#      - name: Verify kubectl configuration
#        run: kubectl config view
#      - name: Verify kubectl get nodes
#        run: |
#          kubectl get nodes

  DIGIT-deployment:
#    if: ${{ github.event_name == 'push' }}
#    needs: Terraform_Infra_Creation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SOLUTIONS_AZURE_CREDENTIALS }}

      - name: Generate kubeconfig
        run: |
          az aks get-credentials --resource-group "solutions-pucar-dev" --name "solutions-dev"
          cat ~/.kube/config > kubeconfig

      - name: Kubectl setup
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          id: install

      - name: Creating namespace
        run: kubectl create namespace egov
        continue-on-error: true

      - name: Verify kubectl get nodes
        run: |
          kubectl get nodes

      - name: Install sops
        run: |
          sudo apt update
          sudo apt install -y age
          mkdir -p $HOME/.config/sops/age/
          echo # public key: ${{ secrets.PUBLIC_AGE_KEY }} > $HOME/.config/sops/age/keys.txt
          echo ${{ secrets.PRIVATE_AGE_KEY }} >> $HOME/.config/sops/age/keys.txt
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
          chmod +x sops-v3.7.1.linux
          sudo mv sops-v3.7.1.linux /usr/local/bin/sops

      - name: sops decryption
        run: |
          sudo sops --decrypt --age ${{ secrets.PUBLIC_AGE_KEY }} $HOME/work/pucar-DevOps/pucar-DevOps/deploy-as-code/charts/environments/solutions-dev-secrets.yaml > env-secrets1.yaml
          cp env-secrets1.yaml $HOME/work/pucar-DevOps/pucar-DevOps/deploy-as-code/charts/environments/solutions-dev-secrets.yaml
#        working-directory: deploy-as-code/charts/environments

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest' # Specify the version of Helm

      - name: Install Helmfile
        uses: helmfile/helmfile-action@v1.9.0
        with:
          helmfile-version: 'v0.150.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff

      - name: Commit Id for Latest Deployment
        run: |
          git clone https://github.com/pucardotorg/Dristi_kerala.git
          cd Dristi_kerala
          git checkout develop
          scheduler_commit=$(git log -1 --pretty=format:%H -- backend/scheduler-svc)
          echo "scheduler_commit=$scheduler_commit" >> $GITHUB_ENV
          payment_calculator_commit=$(git log -1 --pretty=format:%H -- backend/payment-calculator-svc)
          echo "payment_calculator_commit=$payment_calculator_commit" >> $GITHUB_ENV
          advocate_commit=$(git log -1 --pretty=format:%H -- backend/advocate)
          echo "advocate_commit=$advocate_commit" >> $GITHUB_ENV
          case_commit=$(git log -1 --pretty=format:%H -- backend/case)
          echo "case_commit=$case_commit" >> $GITHUB_ENV
          casemanagement_commit=$(git log -1 --pretty=format:%H -- backend/casemanagement)
          echo "casemanagement_commit=$casemanagement_commit" >> $GITHUB_ENV
          evidence_commit=$(git log -1 --pretty=format:%H -- backend/evidence)
          echo "evidence_commit=$evidence_commit" >> $GITHUB_ENV
          hearing_commit=$(git log -1 --pretty=format:%H -- backend/hearing)
          echo "hearing_commit=$hearing_commit" >> $GITHUB_ENV
          order_commit=$(git log -1 --pretty=format:%H -- backend/order)
          echo "order_commit=$order_commit" >> $GITHUB_ENV
          task_commit=$(git log -1 --pretty=format:%H -- backend/task)
          echo "task_commit=$task_commit" >> $GITHUB_ENV
          digit_ui_commit=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "digit_ui_commit=$digit_ui_commit" >> $GITHUB_ENV
          billing_service_commit=$(git log -1 --pretty=format:%H -- backend/billing-service)
          echo "billing_service_commit=$billing_service_commit" >> $GITHUB_ENV
          collection_service_commit=$(git log -1 --pretty=format:%H -- backend/collection-services)
          echo "collection_service_commit=$collection_service_commit" >> $GITHUB_ENV
          individual_commit=$(git log -1 --pretty=format:%H -- backend/individual)
          echo "individual_commit=$individual_commit" >> $GITHUB_ENV
          esign_interceptor_commit=$(git log -1 --pretty=format:%H -- backend/esign-interceptor)
          echo "esign_interceptor_commit=$esign_interceptor_commit" >> $GITHUB_ENV
          esign_svc_commit=$(git log -1 --pretty=format:%H -- backend/e-sign-svc)
          echo "esign_svc_commit=$esign_svc_commit" >> $GITHUB_ENV
          application_commit=$(git log -1 --pretty=format:%H -- backend/application)
          echo "application_commit=$application_commit" >> $GITHUB_ENV          
          summons_svc_commit=$(git log -1 --pretty=format:%H -- backend/summons-svc)
          echo "summons_svc_commit=$summons_svc_commit" >> $GITHUB_ENV  
          analytics_commit=$(git log -1 --pretty=format:%H -- backend/analytics)
          echo "analytics_commit=$analytics_commit" >> $GITHUB_ENV 
          epost_tracker_commit=$(git log -1 --pretty=format:%H -- backend/epost-tracker)
          echo "epost_tracker_commit=$epost_tracker_commit" >> $GITHUB_ENV 
          etreasury_commit=$(git ls-remote https://github.com/pucardotorg/etreasury_kerala.git develop | awk '{print $1}')
          echo "etreasury_commit=$etreasury_commit" >> $GITHUB_ENV  

      - name: digit deployment
        run: |
          helmfile -l deployment=pucar -f digit-helmfile.yaml apply --include-needs=true \
            --set scheduler.image.tag=v1.0.0-${{ env.scheduler_commit }} \
            --set scheduler.initContainers.dbMigration.image.tag=v1.0.0-${{ env.scheduler_commit }} \
            --set payment-calculator.image.tag=v1.0.0-${{ env.payment_calculator_commit }} \
            --set payment-calculator.initContainers.dbMigration.image.tag=v1.0.0-${{ env.payment_calculator_commit }} \
            --set digit-ui.image.tag=v1.0.0-${{ env.digit_ui_commit }} \
            --set advocate.image.tag=v1.0.0-${{ env.advocate_commit }} \
            --set advocate.initContainers.dbMigration.image.tag=v1.0.0-${{ env.advocate_commit }} \
            --set case.image.tag=v1.0.0-${{ env.case_commit }} \
            --set case.initContainers.dbMigration.image.tag=v1.0.0-${{ env.case_commit }} \
            --set casemanagement.image.tag=v1.0.0-${{ env.casemanagement_commit }} \
            --set casemanagement.initContainers.dbMigration.image.tag=v1.0.0-${{ env.casemanagement_commit }} \
            --set evidence.image.tag=v1.0.0-${{ env.evidence_commit }} \
            --set evidence.initContainers.dbMigration.image.tag=v1.0.0-${{ env.evidence_commit }} \
            --set hearing.image.tag=v1.0.0-${{ env.hearing_commit }} \
            --set hearing.initContainers.dbMigration.image.tag=v1.0.0-${{ env.hearing_commit }} \
            --set order.image.tag=v1.0.0-${{ env.order_commit }} \
            --set order.initContainers.dbMigration.image.tag=v1.0.0-${{ env.order_commit }} \
            --set task.image.tag=v1.0.0-${{ env.task_commit }} \
            --set task.initContainers.dbMigration.image.tag=v1.0.0-${{ env.task_commit }} \
            --set billing-service.image.tag=v1.0.0-${{ env.billing_service_commit }} \
            --set billing-service.initContainers.dbMigration.image.tag=v1.0.0-${{ env.billing_service_commit }} \
            --set collection-services.image.tag=v1.0.0-${{ env.collection_service_commit }} \
            --set collection-services.initContainers.dbMigration.image.tag=v1.0.0-${{ env.collection_service_commit }} \
            --set individual.image.tag=v1.0.0-${{ env.individual_commit }} \
            --set individual.initContainers.dbMigration.image.tag=v1.0.0-${{ env.individual_commit }} \
            --set e-sign-svc.image.tag=v1.0.0-${{ env.esign_svc_commit }} \
            --set esign-interceptor.image.tag=v1.0.0-${{ env.esign_interceptor_commit }} \
            --set application.image.tag=v1.0.0-${{ env.application_commit }} \
            --set application.initContainers.dbMigration.image.tag=v1.0.0-${{ env.application_commit }} \
            --set analytics.image.tag=v1.0.0-${{ env.analytics_commit }} \
            --set epayments.image.tag=v1.0.0-${{ env.etreasury_commit }} \
            --set etreasury.image.tag=v1.0.0-${{ env.etreasury_commit }} \
            --set etreasury.initContainers.dbMigration.image.tag=v1.0.0-${{ env.etreasury_commit }} \
            --set epost-tracker.image.tag=v1.0.0-${{ env.epost_tracker_commit }} \
            --set epost-tracker.initContainers.dbMigration.image.tag=v1.0.0-${{ env.epost_tracker_commit }} \
            --set summons-svc.image.tag=v1.0.0-${{ env.summons_svc_commit }} \
            --set summons-svc.initContainers.dbMigration.image.tag=v1.0.0-${{ env.summons_svc_commit }} 

        working-directory: deploy-as-code
        env:
          HELMFILE_ENV: "solutions-dev"
